<a href="https://colab.research.google.com/github/marmbright/Project1/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1: Getting started with Numpy

Let's spend a few minutes just learning some of the fundamentals of Numpy. (pronounced as num-pie **not num-pee**) 

### what is numpy
Numpy is a Python library that support large, multi-dimensional arrays and matrices. 

Let's look at an example. Suppose we start with a little table:

| a  | b | c  |  d | e |
| :---: | :---: | :---: | :---: | :---: |
| 0 | 1 | 2 | 3 | 4 |
|10| 11| 12 | 13 | 14|
|20| 21 | 22 | 23 | 24 |
|30 | 31 | 32 | 33 | 34 |
|40 |41 | 42 | 43 | 44 |

and I simply want to add 10 to each cell:

| a  | b | c  |  d | e |
| :---: | :---: | :---: | :---: | :---: |
| 10 | 11 | 12 | 13 | 14 |
|20| 21| 22 | 23 | 24|
|30| 31 | 32 | 33 | 34 |
|40 | 41 | 42 | 43 | 44 |
|50 |51 | 52 | 53 | 54 |

To make things interesting, instead of a a 5 x5 array, let's make it 1,000x1,000 -- so 1 million cells!

First, let's construct it in generic Python

In [ ]:
a = [[x + y * 1000 for x in range(1000)] for y in range(1000)]


Instead of glossing over the first code example in the course, take your time, go back, and parse it out so you understand it. Test it out and see what it looks like. For example, how would you change the example to make a 10x10 array called `a2`? execute the code here:

In [ ]:
a2 = a = [[x + y * 10 for x in range(10)] for y in range(10)]

print(a2)


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49], [50, 51, 52, 53, 54, 55, 56, 57, 58, 59], [60, 61, 62, 63, 64, 65, 66, 67, 68, 69], [70, 71, 72, 73, 74, 75, 76, 77, 78, 79], [80, 81, 82, 83, 84, 85, 86, 87, 88, 89], [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


Now let's take a look at the value of a2:

In [ ]:
a2

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
 [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
 [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]

Now that we understand that line of code let's go on and write a function that will add 10 to each cell in our original 1000x1000 matrix.


In [ ]:
def addToArr(sizeof):
    for i in range(sizeof):
        for j in range(sizeof):
            a[i][j] = a[i][j] + 10


As you can see, we iterate over the array with nested for loops. 

Let's take a look at how much time it takes to run that function:

In [ ]:
%time addToArr(10)

CPU times: user 30 µs, sys: 0 ns, total: 30 µs
Wall time: 34.6 µs


My results were:

    CPU times: user 145 ms, sys: 0 ns, total: 145 ms
    Wall time: 143 ms

So about 1/7 of a second. 

### Doing in using Numpy
Now do the same using Numpy.


We can construct the array using
    
    arr = np.arange(1000000).reshape((1000,1000))

Not sure what that line does? Numpy has great online documentation. [Documentation for np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) says it "Return evenly spaced values within a given interval." Let's try it out:

In [ ]:
import numpy as np
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

So `np.arange(10)` creates a matrix of 16 sequential integers. [The documentation for reshape](https://numpy.org/doc/1.18/reference/generated/numpy.reshape.html) says, as the name suggests, "Gives a new shape to an array without changing its data."  Suppose we want to reshape our 1 dimensional matrix of 16 integers to a 4x4 one. we can do:

In [ ]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

As you can see it is pretty easy to find documentation on Numpy.

Back to our example of creating a 1000x1000 matrix, we now can time how long it takes to add 10 to each cell.

    %time arr = arr + 10
    
Let's put this all together:

In [ ]:
import numpy as np
arr = np.arange(1000000).reshape((1000,1000))
%time arr = arr + 1

CPU times: user 2.34 ms, sys: 0 ns, total: 2.34 ms
Wall time: 3.65 ms


My results were

    CPU times: user 1.26 ms, sys: 408 µs, total: 1.67 ms
    Wall time: 1.68 ms

So, depending on your computer, somewhere around 25 to 100 times faster. **That is phenomenally faster!**

And Numpy is even fast in creating arrays:

#### the generic Python way

In [ ]:
%time a = [[x + y * 1000 for x in range(1000)] for y in range(1000)]

CPU times: user 111 ms, sys: 8.79 ms, total: 120 ms
Wall time: 119 ms


My results were

    CPU times: user 92.1 ms, sys: 11.5 ms, total: 104 ms
    Wall time: 102 ms

#### the Numpy way

In [ ]:
%time arr = np.arange(1000000).reshape((1000,1000))

CPU times: user 2.63 ms, sys: 87 µs, total: 2.72 ms
Wall time: 2.29 ms


What are your results?

<h3 style="color:red">Q1. Speed</h3>
<span style="color:red">Suppose I want to create an array with 10,000 by 10,000 cells. Then I want to add 1 to each cell. How much time does this take using generic Python arrays and using Numpy arrays?</span>

#### in Python
(be patient -- this may take a number of seconds)

In [ ]:
a = [[x + y * 10000 for x in range(10000)] for y in range(10000)]

def addToArr(sizeof):
    for i in range(sizeof):
        for j in range(sizeof):
            a[i][j] = a[i][j] + 1

%time addToArr(10000)

CPU times: user 12.6 s, sys: 0 ns, total: 12.6 s
Wall time: 12.6 s


#### in Numpy

In [ ]:
arr = np.arange(100000000).reshape((10000,10000))

%time arr = arr + 1

CPU times: user 111 ms, sys: 324 ms, total: 435 ms
Wall time: 436 ms


### built in functions
In addition to being faster, numpy has a wide range of built in functions. So, for example, instead of you writing code to calculate the mean or sum or standard deviation of a multidimensional array you can just use numpy:

In [ ]:
arr.mean()

50000000.5

In [ ]:
arr.sum()

5000000050000000

In [ ]:
 arr.std()

28867513.459478058

So not only is it faster, but it minimizes the code you have to write. A win, win.

Let's continue with some basics.

## numpy examined 
So Numpy is a library containing a super-fast n-dimensional array object and a load of functions that can operate on those arrays. To use numpy, we must first load the library into our code and we do that with the statement:


In [ ]:
 import numpy as np

Perhaps most of you are saying "fine, fine, I know this already", but let me catch others up to speed. This is just one of several ways we can load a library into Python. We could just say:

In [ ]:
 import numpy

and everytime we need to use one of the functions built in
to numpy we would need to preface that function with `numpy` . So for example, we could create an array with


In [ ]:
arr = numpy.array([1, 2, 3, 4, 5])

If we got tired of writing `numpy` in front of every function, instead of typing

In [ ]:
import numpy

we could write:

In [ ]:
from numpy import *

(where that * means 'everything' and the whole expression means import everything from the numpy library).  Now we can use any numpy function without putting numpy in front of it:

In [ ]:
arr = array([1, 2, 3, 4, 5])

This may at first seem like a good idea, but it is considered bad form by Python developers. 

The solution is to use what we initially introduced:

In [3]:
 import numpy as np

this makes `np` an alias for numpy. so now we would put *np* in front of numpy functions.

In [ ]:
 arr = np.array([1, 2, 3, 4, 5])

Of course we could use anything as an alias for numpy:

In [ ]:
import numpy as myCoolSneakers
arr = myCoolSneakers.array([1, 2, 3, 4, 5])


But it is convention among data scientists, machine learning experts, and the cool kids to use np.  One big benefit of this convention is that it makes the code you write more understandable to others and vice versa (I don't need to be scouring your code to find out what `myCoolSneakers.array` does)

## creating arrays

An Array in Numpy is called an `ndarray` for n-dimensional array.  As we will see, they share some similarities with Python lists. We have already seen how to create one:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

and to display what `arr` equals

In [ ]:
arr

array([1, 2, 3, 4, 5])

This is a one dimensional array. The position of an element in the array is called the index. The first element of the array is at index 0, the next at index 1 and so on. We can get the item at a particular index by using the syntax:

In [ ]:
 arr[0]

1

In [ ]:
arr[3]

4

We can create a 2 dimensional array that looks like

      10  20  30
      40  50  60
 
by:


In [ ]:
 arr = np.array([[10, 20, 30], [40, 50, 60]])

and we can show the contents of that array just be using the name of the array, `arr`


In [ ]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

We don't need to name arrays `arr`, we can name them anything we want. 

In [ ]:
ratings = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
ratings

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

So far, we've been creating numpy arrays by using Python lists. We can make that more explicit by first creating the Python list and then using it to create the ndarray:

In [ ]:
pythonArray = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
sweet = np.array(pythonArray)
sweet

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

We can also create an array of all zeros or all ones directly:

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### indexing
Indexing elements in ndarrays works pretty much the same as it does in Python. We have already seen one example, here is another example with a one dimensional array:


In [ ]:
temperatures = np.array([48, 44, 37, 35, 32, 29, 33, 36, 42])
temperatures[0]

48

In [ ]:
temperatures[3]

35

and a two dimensional one:

In [ ]:
sample = np.array([[10, 20, 30], [40, 50, 60]])
sample[0][1]

20

For numpy ndarrays we can also use a comma to separate the indices of multi-dimensional arrays:

In [ ]:
sample[1,2]

60

And, like Python you can also get a slice of an array. First, here is the basic Python example:

In [ ]:
a = [10, 20, 30, 40, 50, 60]
b = a[1:4]
b

[20, 30, 40]

and the similar numpy example:

In [ ]:
aarr = np.array(a)
barr = aarr[1:4]
barr

array([20, 30, 40])

### Something  wacky to remember
But there is a difference between Python arrays and numpy ndarrays. If I alter the array `b` in Python the orginal `a` array is not altered:

In [ ]:
b[1] = b[1] + 5

In [ ]:
b

[20, 35, 40]

In [ ]:
a

[10, 20, 30, 40, 50, 60]

but if we do the same in numpy:

In [ ]:
barr[1] = barr[1] + 5

In [ ]:
barr

array([20, 35, 40])

In [ ]:
aarr

array([10, 20, 35, 40, 50, 60])

we see that the original array is altered since we modified the slice. This may seem wacky to you, or maybe it doesn't. In any case, it is something you will get used to. For now, just be aware of this. 

## functions on arrays

Numpy has a wide range of array functons. Here is just a sample.

### Unary functions

#### absolute value

In [4]:
arr = np.array([-2, 12, -25, 0])
arr2 = np.abs(arr)
arr2

array([ 2, 12, 25,  0])

In [5]:
arr = np.array([[-2, 12], [-25, 0]])
arr2 = np.abs(arr)
arr2               

array([[ 2, 12],
       [25,  0]])

#### square

In [6]:
arr = np.array([-1, 2, -3, 4])
arr2 = np.square(arr)
arr2

array([ 1,  4,  9, 16])

#### squareroot

In [7]:
arr = np.array([[4, 9], [16, 25]])
arr2 = np.sqrt(arr)
arr2

array([[2., 3.],
       [4., 5.]])

## Binary functions

#### add /subtract / multiply / divide


In [9]:
arr1 = np.array([[10, 20], [30, 40]])
arr2 = np.array([[1, 2], [3, 4]])
np.add(arr1, arr2)

array([[11, 22],
       [33, 44]])

In [10]:
np.subtract(arr1, arr2)

array([[ 9, 18],
       [27, 36]])

In [11]:
np.multiply(arr1, arr2)

array([[ 10,  40],
       [ 90, 160]])

In [12]:
np.divide(arr1, arr2)

array([[10., 10.],
       [10., 10.]])

#### maximum / minimum


In [14]:
arr1 = np.array([[10, 2], [3, 40]])
arr2 = np.array([[1, 20], [30, 4]])
np.maximum(arr1, arr2)

array([[10, 20],
       [30, 40]])

#### these are just examples. There are more unary and binary functions

## Numpy Uber
lets say I have Uber drivers at various intersections around Austin. I will represent that as a set of x,y coordinates.

 | Driver |xPos | yPos |
 | :---: | :---: | :---: |
 | Ann | 4 | 5 |
 | Clara | 6 | 6 |
 | Dora | 3 | 1 |
 | Erica | 9 | 5 |
 
 
 Now I would like to find the closest driver to a customer who is at 6, 3.
 And to further define *closest* I am going to use what is called **Manhattan Distance**. Roughly put, Manhattan distance is distance if you followed streets. Ann, for example, is two blocks West of our customer and two blocks north. So the Manhattan distance from Ann to our customer is `2+2` or `4`. 
 
 First, to make things easy (and because the data in a numpy array must be of the same type), I will represent the x and y positions in one numpy array and the driver names in another:

In [15]:
locations = np.array([[4, 5], [6, 6], [3, 1], [9,5]])
locations

array([[4, 5],
       [6, 6],
       [3, 1],
       [9, 5]])

In [16]:
drivers = np.array(["Ann", "Clara", "Dora", "Erica"])

Our customer is at

In [17]:
cust = np.array([6, 3])

now we are going to figure out the distance between each of our drivers and the customer

In [18]:
xydiff = locations - cust
xydiff

array([[-2,  2],
       [ 0,  3],
       [-3, -2],
       [ 3,  2]])

NOTE: displaying the results with `xydiff` isn't a necessary step. I just like seeing intermediate results.

Ok. now I am goint to sum the absolute values:

In [19]:
distances =np.abs(xydiff).sum(axis = 1)
distances

array([4, 3, 5, 5])

So the output is the array `[4, 3, 5, 5]` which shows that Ann is 4 away from our customer; Clara is 3 away and so on.

Now I am going to sort these using `argsort`:

In [20]:
sorted = np.argsort(distances)
sorted

array([1, 0, 2, 3])

`argsort` returns an array of sorted indices. So the element at position 1 is the smallest followed by the element at position 0 and so on.

Next, I am going to get the first element of that array (in this case 1) and find the name of the driver at that position in the `drivers` array

In [21]:
drivers[sorted[0]]

'Clara'

<h3 style="color:red">Q2. You Try</h3>
<span style="color:red">Can you put all the above in a function. that takes 3 arguments, the location array, the array containing the names of the drivers, and the array containing the location of the customer. It should return the name of the closest driver.</span>


In [23]:
def findDriver(distanceArr, driversArr, customerArr):
   result = ''
   xydiff = distanceArr - customerArr
   distances = np.abs(xydiff).sum(axis = 1)
   sorted = np.argsort(distances)
   result = driversArr[sorted[0]]
   return result
print(findDriver(locations, drivers, cust)) # this should return Clara

Clara


### CONGRATULATIONS

Even though this is just an intro to Numpy, I am going to throw some math at you. So far we have been looking at a two dimensional example, x and y (or North-South and East-West) and our distance formula for the distance, Dist between Ann, A and Customer C is

$$ DIST_{AC} = |A_x - C_x | + |A_y - C_y | $$

Now I am going to warp this a bit. In this example, each driver is represented by an array (as is the customer) So, Ann is represented by `[1,2]` and the customer by `[3,4]`. So Ann's 0th element is 1 and the customer's 0th element is 3. And, sorry, computer science people start counting at 0 but math people (and all other normal people) start at 1 so we  can rewrite the above formula as:

$$ DIST_{AC} = |A_1 - C_1 | + |A_2 - C_2 | $$

That's the distance formula for Ann and the Customer. We can make the formula by saying the distance between and two people, let's call them *x* and *y* is


$$ DIST_{xy} = |x_1 - y_1 | + |x_2 - y_2 | $$

That is the formula for  2 dimensional Manhattan Distance. We can imagine a three dimensional case.  

$$ DIST_{xy} = |x_1 - y_1 | + |x_2 - y_2 | + |x_3 - y_3 | $$

and we can generalize the formula to the n-dimensional case.
 
$$ DIST_{xy}=\sum_{i=1}^n |x_i - y_i| $$

Just in time for a five dimensional example:


# The Amazing 5D Music example

Guests went into a listening booth and rated the following tunes:

* [Janelle Monae Tightrope](https://www.youtube.com/watch?v=pwnefUaKCbc)
* [Major Lazer - Cold Water](https://www.youtube.com/watch?v=nBtDsQ4fhXY)
* [Tim McGraw - Humble & Kind](https://www.youtube.com/watch?v=awzNHuGqoMc)
* [Maren Morris - My Church](https://www.youtube.com/watch?v=ouWQ25O-Mcg)
* [Hailee Steinfeld - Starving](https://www.youtube.com/watch?v=xwjwCFZpdns)


Here are the results:

| Guest  | Janelle Monae  | Major Lazer  | Tim McGraw  |  Maren Morris | Hailee Steinfeld| 
|---|---|---|---|---|---|
|  Ann | 4  |  5 | 2  |  1 | 3 |
| Ben  |  3 |  1 |  5 | 4  | 2|
| Jordyn  | 5  |  5 | 2  | 2  | 3|
|  Sam | 4 | 1 | 4 | 4 | 1|
| Hyunseo | 1 | 1 | 5 | 4 | 1 |
| Ahmed | 4 | 5 | 3 |  3 | 1 |

So Ann, for example, really liked Major Lazer and Janelle Monae but didn't care much for Maren Morris.

Let's set up a few numpy arrays.


In [24]:
customers = np.array([[4, 5, 2, 1, 3],
                      [3, 1, 5, 4, 2],
                      [5, 5, 2, 2, 3],
                      [4, 1, 4, 4, 1], 
                      [1, 1, 5, 4, 1],
                      [4, 5, 3, 3, 1]])

customerNames = np.array(["Ann", "Ben", 'Jordyn', "Sam", "Hyunseo", "Ahmed"])



Now let's set up a few new customers:

In [25]:
mikaela = np.array([3, 2, 4, 5, 4])
brandon = np.array([4, 5, 1, 2, 3])

Now we would like to determine  which of our current customers is closest to Mikaela and which to Brandon.
<h3 style="color:red">Q3. You Try</h3>
<span style="color:red">Can you write a function findClosest that takes 3 arguments: customers, customerNames, and an array representing one customer's ratings and returns the name of the closest customer?</span>

Let's break this down a bit.

1. Which line in the Numpy Uber section above will create a new array which is the result of subtracting the Mikaela array from each row of the customers array resulting in

```
array([[ 1,  3, -2, -4, -1],
       [ 0, -1,  1, -1, -2],
       [ 2,  3, -2, -3, -1],
       [ 1, -1,  0, -1, -3],
       [-2, -1,  1, -1, -3],
       [ 1,  3, -1, -2, -3]])
       ```


In [26]:
# TO DO

2. Which line above will take the array you created and generate a single integer distance for each row representing how far away that row is from Mikaela?  The results will look like:

```
    array([11,  5, 11,  6,  8, 10])
```

In [ ]:
# TO DO 


Finally, we want a sorted array of indices, the zeroth element of that array will be the closest row to Mikaela, the next element will be the next closest and so on. The result should be

```
array([1, 3, 4, 5, 0, 2])
```


In [ ]:
# TO DO


Finally we need the name of the person that is the closest. 

In [ ]:
# TO DO

Okay, time to put it all together. Can you combine all the code you wrote above to finish the following function? So x is the new person and we want to find the closest customer to x.

In [ ]:
def findClosest(customers, customerNames, x):
   # TO DO
   return ''


print(findClosest(customers, customerNames, mikaela)) # Should print Ben
print(findClosest(customers, customerNames, brandon)) # Should print Ann

## Numpy Amazon

We are going to start with the same array we did way up above:

 
 | Drone |xPos | yPos |
 | :---: | :---: | :---: |
 | wing_1a | 4 | 5 |
 | wing_2a | 6 | 6 |
 | wing_3a | 3 | 1 |
 | wing_4a | 9 | 5 |
 
 But this time, instead of Uber drivers, think of these as positions of [Alphabet's Wing delivery drones](https://wing.com/). 
 Now we would like to find the closest drone to a customer who is at 7, 1.
 
With the previous example we used Manhattan Distance.  With drones, we can compute the distance as the crow flies -- or Euclidean Distance.  We probably learned how to do this way back in 7th grade when we learned the Pythagorean Theorem which states:

$$c^2 = a^2 + b^2$$

Where *c* is the hypotenuse and *a* and *b* are the two other sides. So, if we want to find *c*:

$$c = \sqrt{a^2 + b^2}$$


If we want to find the distance between the drone and a customer, *x* and *y* in the formula becomes

$$Dist_{xy} = \sqrt{(x_1-y_1)^2 + (x_2-y_2)^2}$$

and for `wing_1a` who is at `[4,5]` and our customer who is at `[7,1]` then the formula becomes:

$$Dist_{xy} = \sqrt{(x_1-y_1)^2 + (x_2-y_2)^2} = \sqrt{(4-7)^2 + (5-1)^2} =\sqrt{-3^2 + 4^2}  = \sqrt{9 + 16} = \sqrt{25} = 5$$

Sweet!  And to generalize this distance formula:

$$Dist_{xy} = \sqrt{(x_1-y_1)^2 + (x_2-y_2)^2}$$

to n-dimensions:

$$Dist_{xy} = \sum_{i=1}^n{\sqrt{(x_i-y_i)^2}}$$




<h4 style="color:red">Q4. You Try</h3>
<span style="color:red">Can you write a function euclidean that takes 3 arguments: droneLocation, droneNames, and an array representing one customer's position and returns the name of the closest drone?</span>

First, a helpful hint:


In [ ]:
arr = np.array([-1, 2, -3, 4])
arr2 = np.square(arr)
arr2

array([ 1,  4,  9, 16])

In [ ]:
locations = np.array([[4, 5], [6, 6], [3, 1], [9,5]])
drivers = np.array(["wing_1a", "wing_2a", "wing_3a", "wing_4a"])
cust = np.array([6, 3])

def euclidean(droneLocation, droneNames, x):
   result = ''
   ### your code here   
   return result
euclidean(locations, drivers, cust) 

''

<h4 style="color:red">Q5. You Try</h3>
<span style="color:red">try your code on the "Amazing 5D Music example. Does it return the same person or a different one?"</span>

In [ ]:
#TBD